# Config

# Main conferences with data
main_confs <- c("ACC", "Big Ten", "SEC", "Pac-12", "A 10",
                "Big East", "Big 12", "C-USA")

# Parameters
params <- list("mens" = list("game" = list(days_back = 700L,
                                           sn_decay = 0.9,
                                           day_decay = 0.006,
                                           pad = 1L,
                                           fill = -24L),
                             "ppp" = list(days_back = 500L,
                                          sn_decay = 0.9,
                                          day_decay = 0.006,
                                          pad_o = 90L,
                                          pad_d = 90L,
                                          fill_o = -0.35,
                                          fill_d = 0.3),
                             "pps" = list(days_back = 800L,
                                          sn_decay = 0.8,
                                          day_decay = 0.005,
                                          pad_o = 90L,
                                          pad_d = 90L,
                                          fill_o = -0.3,
                                          fill_d = 0.25),
                             "poss_length" = list(days_back = 600L,
                                                  sn_decay = 1,
                                                  day_decay = 0.01,
                                                  pad_o = 90L,
                                                  pad_d = 90L,
                                                  fill_o = 0,
                                                  fill_d = 0),
                             "lme4" = list(days_back = 500L,
                                           fill_o = -0.1,
                                           fill_d = 0.1,
                                           pad_o = 50L,
                                           pad_d = 35L),
                             "matchup" = list(pad = 10L,
                                              pad_n = 6L,
                                              fill = -0.01),
                             "roll" = list(pad = 15L,
                                           len = 10L,
                                           type = "e")),
               "womens" = list("game" = list(days_back = 800L,
                                             sn_decay = 1.6,
                                             day_decay = 0.006,
                                             pad = 1L,
                                             fill = -20L),
                               "ppp" = list(days_back = 500L,
                                            sn_decay = 1.7,
                                            day_decay = 0.007,
                                            pad_o = 90L,
                                            pad_d = 90L,
                                            fill_o = -0.35,
                                            fill_d = 0.25),
                               "pps" = list(days_back = 800L,
                                            sn_decay = 0.9,
                                            day_decay = 0.006,
                                            pad_o = 90L,
                                            pad_d = 90L,
                                            fill_o = -0.35,
                                            fill_d = 0.15),
                               "poss_length" = list(days_back = 400L,
                                                    sn_decay = 1.9,
                                                    day_decay = 0.012,
                                                    pad_o = 90L,
                                                    pad_d = 70L,
                                                    fill_o = 0,
                                                    fill_d = 0),
                               "lme4" = list(days_back = 500L,
                                             fill_o = -0.1,
                                             fill_d = 0.1,
                                             pad_o = 40L,
                                             pad_d = 25L),
                               "matchup" = list(pad = 11L,
                                                pad_n = 6L,
                                                fill = -0.07),
                               "roll" = list(pad = 30L,
                                             len = 10L,
                                             type = "e")))

xgb_params <- list("mens" = list("ppp" = list("lr" = 0.03,
                                              "md" = 2L,
                                              "rnd" = 391L),
                                 "poss" = list("lr" = 0.03,
                                               "md" = 3L,
                                               "rnd" = 998L),
                                 "game" = list("lr" = 0.03,
                                               "md" = 2L,
                                               "rnd" = 228L)),
                   "womens" = list("ppp" = list("lr" = 0.01,
                                                "md" = 4L,
                                                "rnd" = 617L),
                                   "poss" = list("lr" = 0.01,
                                                 "md" = 6L,
                                                 "rnd" = 617L),
                                   "game" = list("lr" = 0.03,
                                                 "md" = 3L,
                                                 "rnd" = 147L)))

# Lower limits for glmnet (increase win prob)
low_limits <- c("off_rest" = 0,
                "off_rest_sq" = 0,
                "off_rest_diff" = 0,
                "off_location_home" = 0,

                "def_distance_away" = 0,
                "def_distance_neutral" = 0,
                "off_no_travel" = 0,

                "home_distance_adv_neutral" = 0,
                "away_distance_neutral" = 0,
                "away_distance_away" = 0,
                "home_no_travel" = 0,

                "home_rest" = 0,
                "home_rest_sq" = 0,
                "home_rest_diff" = 0,

                "off_home" = 0,
                # "off_matchup_adj" = 0,
                "off_matchup_adj_diff" = 0,
                "home_matchup_adj_diff" = 0,
                "home_pred_ppp_diff" = 0,
                "off_ppp" = 0,
                "off_pps" = 0,
                "off_epps" = 0,
                # "ridge_points_off" = 0,
                "home_ridge_points_diff" = 0,
                "ridge_points_off_diff" = 0,
                "ridge_off_ppp_diff" = 0,
                "ridge_off_pps_diff" = 0,
                "home_off_lme4_ppp_diff" = 0,
                "off_lme4_ppp_diff" = 0,
                "off_lme4_epps_diff" = 0,

                "def_ppp" = 0,
                "def_pps" = 0,
                "def_epps" = 0,

                "weight_winning" = 0,
                "weight_losing" = 0,
                "weight" = 0,

                "b2b_home" = 0)

# Upper limits for glmnet (decrease win prob)
up_limits <- c("def_rest" = 0,
               "def_rest_sq" = 0,

               "away_rest" = 0,
               "away_rest_sq" = 0,

               "off_distance_away" = 0,
               "off_distance_neutral" = 0,
               "def_no_travel" = 0,

               "home_distance_neutral" = 0,
               "away_no_travel" = 0,

               "tied" = 0,

               "ridge_points_def" = 0,
               "home_def_lme4_ppp_diff" = 0,

               "b2b_road" = 0,
               "neutral" = 0)

region_seeds <- list(
  `16` = list(
    `16` = 0,
    `1` = 1,
    `8` = 2,
    `9` = 2,
    `5` = 3,
    `12` = 3,
    `4` = 3,
    `13` = 3,
    `6` = 4,
    `11` = 4,
    `3` = 4,
    `14` = 4,
    `7` = 4,
    `10` = 4,
    `2` = 4,
    `15` = 4
  ),
  `1` = list(
    `16` = 1,
    `8` = 2,
    `9` = 2,
    `5` = 3,
    `12` = 3,
    `4` = 3,
    `13` = 3,
    `6` = 4,
    `11` = 4,
    `3` = 4,
    `14` = 4,
    `7` = 4,
    `10` = 4,
    `2` = 4,
    `15` = 4
  ),
  `8` = list(
    `9` = 1,
    `16` = 2,
    `1` = 2,
    `5` = 3,
    `12` = 3,
    `4` = 3,
    `13` = 3,
    `6` = 4,
    `11` = 4,
    `3` = 4,
    `14` = 4,
    `7` = 4,
    `10` = 4,
    `2` = 4,
    `15` = 4
  ),
  `9` = list(
    `8` = 1,
    `16` = 2,
    `1` = 2,
    `5` = 3,
    `12` = 3,
    `4` = 3,
    `13` = 3,
    `6` = 4,
    `11` = 4,
    `3` = 4,
    `14` = 4,
    `7` = 4,
    `10` = 4,
    `2` = 4,
    `15` = 4
  ),
  `5` = list(
    `12` = 1,
    `4` = 2,
    `13` = 2,
    `8` = 3,
    `9` = 3,
    `16` = 3,
    `1` = 3,
    `6` = 4,
    `11` = 4,
    `3` = 4,
    `14` = 4,
    `7` = 4,
    `10` = 4,
    `2` = 4,
    `15` = 4
  ),
  `12` = list(
    `5` = 1,
    `4` = 2,
    `13` = 2,
    `8` = 3,
    `9` = 3,
    `16` = 3,
    `1` = 3,
    `6` = 4,
    `11` = 4,
    `3` = 4,
    `14` = 4,
    `7` = 4,
    `10` = 4,
    `2` = 4,
    `15` = 4
  ),
  `4` = list(
    `13` = 1,
    `5` = 2,
    `12` = 2,
    `8` = 3,
    `9` = 3,
    `16` = 3,
    `1` = 3,
    `6` = 4,
    `11` = 4,
    `3` = 4,
    `14` = 4,
    `7` = 4,
    `10` = 4,
    `2` = 4,
    `15` = 4
  ),
  `13` = list(
    `4` = 1,
    `5` = 2,
    `12` = 2,
    `8` = 3,
    `9` = 3,
    `16` = 3,
    `1` = 3,
    `6` = 4,
    `11` = 4,
    `3` = 4,
    `14` = 4,
    `7` = 4,
    `10` = 4,
    `2` = 4,
    `15` = 4
  ),
  `6` = list(
    `11` = 1,
    `3` = 2,
    `14` = 2,
    `7` = 3,
    `10` = 3,
    `2` = 3,
    `15` = 3,
    `4` = 4,
    `13` = 4,
    `5` = 4,
    `12` = 4,
    `8` = 4,
    `9` = 4,
    `16` = 4,
    `1` = 4
  ),
  `11` = list(
    `6` = 1,
    `3` = 2,
    `14` = 2,
    `7` = 3,
    `10` = 3,
    `2` = 3,
    `15` = 3,
    `4` = 4,
    `13` = 4,
    `5` = 4,
    `12` = 4,
    `8` = 4,
    `9` = 4,
    `16` = 4,
    `1` = 4
  ),
  `3` = list(
    `14` = 1,
    `6` = 2,
    `11` = 2,
    `7` = 3,
    `10` = 3,
    `2` = 3,
    `15` = 3,
    `4` = 4,
    `13` = 4,
    `5` = 4,
    `12` = 4,
    `8` = 4,
    `9` = 4,
    `16` = 4,
    `1` = 4
  ),
  `14` = list(
    `3` = 1,
    `6` = 2,
    `11` = 2,
    `7` = 3,
    `10` = 3,
    `2` = 3,
    `15` = 3,
    `4` = 4,
    `13` = 4,
    `5` = 4,
    `12` = 4,
    `8` = 4,
    `9` = 4,
    `16` = 4,
    `1` = 4
  ),
  `7` = list(
    `10` = 1,
    `2` = 2,
    `15` = 2,
    `3` = 3,
    `14` = 3,
    `6` = 3,
    `11` = 3,
    `4` = 4,
    `13` = 4,
    `5` = 4,
    `12` = 4,
    `8` = 4,
    `9` = 4,
    `16` = 4,
    `1` = 4
  ),
  `10` = list(
    `7` = 1,
    `2` = 2,
    `15` = 2,
    `3` = 3,
    `14` = 3,
    `6` = 3,
    `11` = 3,
    `4` = 4,
    `13` = 4,
    `5` = 4,
    `12` = 4,
    `8` = 4,
    `9` = 4,
    `16` = 4,
    `1` = 4
  ),
  `2` = list(
    `15` = 1,
    `7` = 2,
    `10` = 2,
    `3` = 3,
    `14` = 3,
    `6` = 3,
    `11` = 3,
    `4` = 4,
    `13` = 4,
    `5` = 4,
    `12` = 4,
    `8` = 4,
    `9` = 4,
    `16` = 4,
    `1` = 4
  ),
  `15` = list(
    `2` = 1,
    `7` = 2,
    `10` = 2,
    `3` = 3,
    `14` = 3,
    `6` = 3,
    `11` = 3,
    `4` = 4,
    `13` = 4,
    `5` = 4,
    `12` = 4,
    `8` = 4,
    `9` = 4,
    `16` = 4,
    `1` = 4
  )
)
